services:
  laravel:
    build:
      context: ./.docker/laravel
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www/html
    env_file:
      - .env
    depends_on:
      - postgres
      - python_service
      - redis
    restart: on-failure

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    restart: on-failure

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure

  python_service:
    build:
      context: ./.docker/python_app
    container_name: python_service
    volumes:
      - ./python_app:/app
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: on-failure

volumes:
  pgdata:
